/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_authentification (void);
GtkWidget* create_Gestion_des_etablissement (void);
GtkWidget* create_Gestion_fichedonneur (void);
GtkWidget* create_Gestion_utilisateur (void);
GtkWidget* create_paneauAdmin (void);
GtkWidget* create_Gestion_des_dons (void);
